steps:
# Step 1: Install Tools, Detect Changes and Execute Terragrunt
- id: 'Install Tools, Detect Changes and Run Terragrunt'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e # Exit immediately on error

    # Install Terraform, Terragrunt, and jq
    apt-get update && apt-get install -y unzip wget jq
    wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
    unzip terraform_1.6.0_linux_amd64.zip
    mv terraform /usr/local/bin/
    chmod +x /usr/local/bin/terraform
    wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.10/terragrunt_linux_amd64
    mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
    chmod +x /usr/local/bin/terragrunt

    if [ -n "$_PR_NUMBER" ]; then
      ACTION="plan"
      git fetch --unshallow
      CHANGED_FILES=$(git diff --name-only origin/$_BASE_BRANCH...origin/$_HEAD_BRANCH)
    else
      ACTION="apply"
      git fetch --depth=2
      CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
    fi

    echo "Action: $$ACTION"
    echo "Changed files: $$CHANGED_FILES"

    # --- UPDATED LOGIC ---
    if echo "$$CHANGED_FILES" | grep -q "modules/" || echo "$$CHANGED_FILES" | grep -q "env.hcl"; then
      echo "Shared module or environment default changed, targeting ALL applications."
      TARGET_DIRS=$(find live -type f -name 'terragrunt.hcl' | xargs dirname)
    else
      TARGET_DIRS=$(echo "$$CHANGED_FILES" | grep -o 'live/[^/]*/[^/]*' | sort | uniq)
    fi

    if [ -z "$$TARGET_DIRS" ]; then
      echo "No infrastructure changes detected. Exiting."
      # Create an empty file to signal that no plans were generated
      touch /workspace/all_plans.txt
      exit 0
    fi

    echo "Target directories to process: $$TARGET_DIRS"

    # Initialize a file to hold all plan outputs
    ALL_PLANS_FILE="/workspace/all_plans.txt"
    > $$ALL_PLANS_FILE

    # Loop through each affected directory
    for DIR in $$TARGET_DIRS; do
      ENV_NAME=$(echo "$$DIR" | cut -d'/' -f2)
      echo "--- Processing environment: $$ENV_NAME in directory $$DIR ---"
      
      cd "$$DIR"

      if [ "$$ACTION" == "plan" ]; then
        # Run plan and append output to the file
        echo -e "\n\n**Plan for $$DIR**\n\`\`\`\n" >> $$ALL_PLANS_FILE
        # Use || true to prevent build failure if plan has changes (non-zero exit code)
        terragrunt plan -no-color >> $$ALL_PLANS_FILE 2>&1 || true
        echo -e "\n\`\`\`" >> $$ALL_PLANS_FILE
      else
        terragrunt apply --terragrunt-non-interactive --auto-approve
      fi
      
      cd - # Go back to the previous directory
    done

# Step 2: Fetch GitHub Token
- id: 'Fetch GitHub Token'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Fetch the secret only if this is a pull request
    if [ -n "$_PR_NUMBER" ]; then
      echo "Fetching GitHub token..."
      gcloud secrets versions access latest --secret=github-token --project=$PROJECT_ID --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/github_token.txt
    else
      echo "Not a PR, skipping token fetch."
    fi

# Step 3: Post Plan to GitHub PR
- id: 'Post Plan to GitHub'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # This step only runs for pull requests
    if [ -n "$_PR_NUMBER" ]; then
      GITHUB_TOKEN=$(cat /workspace/github_token.txt)
      ALL_PLANS_FILE="/workspace/all_plans.txt"

      # Check if there are any plans to post
      if [ ! -s $$ALL_PLANS_FILE ]; then
        COMMENT_BODY="✅ Terragrunt Plan successful. No changes detected."
      else
        # Construct the comment body using printf to avoid heredoc issues
        PLAN_CONTENT=$(cat $$ALL_PLANS_FILE)
        COMMENT_BODY=$(printf "<details><summary>Click to expand</summary>\n\n%s\n\n</details>" "$$PLAN_CONTENT")
      fi

      # The API requires the body to be a valid JSON string.
      # We use jq to format it correctly.
      JSON_PAYLOAD=$(jq -n --arg body "$$COMMENT_BODY" '{body: $body}')

      curl -s -X POST \
        -H "Authorization: token $$GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/$REPO_FULL_NAME/issues/$_PR_NUMBER/comments" \
        -d "$$JSON_PAYLOAD"
    else
      echo "Not a PR. Skipping comment."
    fi

options:
  logging: CLOUD_LOGGING_ONLY