steps:
# Step 1: Install Tools
- id: 'Install Tools'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    apk add --no-cache git
    wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.10/terragrunt_linux_amd64
    mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
    chmod +x /usr/local/bin/terragrunt

# Step 2: Detect Changes and Execute Terragrunt
- id: 'Detect Changes and Run Terragrunt'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e # Exit immediately on error

    if [ "$_IS_PR" == "true" ]; then
      ACTION="plan"
      git fetch origin main
      CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
    else
      ACTION="apply"
      CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
    fi

    echo "Action: $$ACTION"
    echo "Changed files: $$CHANGED_FILES"

    # --- UPDATED LOGIC ---
    # Detect changes in shared modules or env.hcl files
    if echo "$$CHANGED_FILES" | grep -q "modules/" || echo "$$CHANGED_FILES" | grep -q "env.hcl"; then
      echo "Shared module or environment default changed, targeting ALL applications."
      # Find all terragrunt.hcl files inside the 'live' directory
      TARGET_DIRS=$(find live -type f -name 'terragrunt.hcl' | xargs dirname)
    else
      # Detect changes in specific application directories inside 'live'
      TARGET_DIRS=$(echo "$$CHANGED_FILES" | grep -o 'live/[^/]*/[^/]*' | sort | uniq)
    fi

    if [ -z "$$TARGET_DIRS" ]; then
      echo "No infrastructure changes detected. Exiting."
      exit 0
    fi

    echo "Target directories to process: $$TARGET_DIRS"

    # Loop through each affected directory (e.g., live/dev/app1)
    for DIR in $$TARGET_DIRS; do
      ENV_NAME=$(echo "$$DIR" | cut -d'/' -f2) # Extracts 'dev' or 'prod'
      echo "--- Processing environment: $$ENV_NAME in directory $$DIR ---"

      case "$$ENV_NAME" in
        dev)
          SERVICE_ACCOUNT="dev-iac-deployer@dev-iac-demo.iam.gserviceaccount.com"
          ;;
        prod)
          SERVICE_ACCOUNT="prod-iac-deployer@prod-iac-demo.iam.gserviceaccount.com"
          ;;
        *)
          echo "Unknown environment: $$ENV_NAME. Skipping."
          continue
          ;;
      esac
      
      cd "$$DIR"

      echo "Using Service Account: $$SERVICE_ACCOUNT for action: $$ACTION"
      gcloud auth print-access-token --impersonate-service-account="$$SERVICE_ACCOUNT" | terraform login

      if [ "$$ACTION" == "plan" ]; then
        terragrunt plan
      else
        terragrunt apply --terragrunt-non-interactive --auto-approve
      fi
      
      # Go back to the root for the next loop (live/dev/app1 -> 3 levels up)
      cd ../../..
    done
options:
  logging: CLOUD_LOGGING_ONLY
